# version: '3'
# services:
#   db:
#     image: mdillon/postgis:10-alpine
#     container_name: "postgres"
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#   app:
#     image: ruby:2.6.5
#     command: "/bin/sh /app/docker-test.sh"
#     ports:
#       - "3001:3000"    
#     volumes:
#       - /home/taneli/environment/<>:/app # this needs to be changed when run
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: postgres://postgres@db/the_oracle	# this part creates a database called 'the_oracle'
#       RAILS_ENV: test
#       RAILS_MASTER_KEY: <>
#       DATABASE_HOST: localhost
#       DATABASE_USER: postgres
#       DATABASE_PASSWORD: postgres
